name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Check Flutter build manually
        run: flutter build web

      - name: Build and Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: /rubenfy/
