name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Generate .env file
        run: |
          cat <<EOF > ./assets/.env
          API_KEY=${{ secrets.FIREBASE_API_KEY }}
          AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}
          PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
          STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}
          MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_ID }}
          APP_ID=${{ secrets.FIREBASE_APP_ID }}
          MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}
          EOF

      - name: Enable web (optional if not already)
        run: flutter config --enable-web

      - name: Build and Deploy
        uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: /rubenfy/